# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: pre-release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - melodic

jobs:
  default:
    strategy:
      matrix:
        distro: [noetic, melodic]

    env:
      ROS_DISTRO: ${{ matrix.distro }}
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache ccache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.distro }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.distro }}-${{ github.sha }}
            ccache-${{ matrix.distro }}
      - name: industrial_ci
        uses: ros-industrial/industrial_ci@master
      - name: upload test artifacts (on failure)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: ${{ env.BASEDIR }}/target_ws/**/test_results/**/*.xml
